"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os.path
import os 
from pathlib import Path
SETTINGS_DIR = os.path.dirname(__file__)
PROJECT_PATH = os.path.join(SETTINGS_DIR, os.pardir)
PROJECT_PATH = os.path.abspath(PROJECT_PATH)
TEMPLATE_PATH = os.path.join(PROJECT_PATH, 'templates')
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '2^)ly=4-=4h79fk3%^6hb2n%#xp3=@6sj2*=kv1r8-vm5kxya9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
#    'django.contrib.admin',
 #   'django.contrib.auth',
 #   'django.contrib.contenttypes',
 #   'django.contrib.sessions',
#    'django.contrib.messages',
#    'django.contrib.staticfiles',  
 #   'code',
 #   'rango',
    'django.contrib.auth' , 
    'django.contrib.contenttypes' , 
    'django.contrib.sessions' ,
    'django.contrib.sites' , 
    'django.contrib.messages' , 
    'django.contrib.staticfiles' , 
    'django.contrib.admin', 
    'django.contrib.admindocs', 
    'rango' ,
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_PATH],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
#DATABASES_PATH = os.path.join(PROJECT_PATH, 'rango.db')
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
      #  'NAME' : DATABASES_PATH ,
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

"""TEMPLATE_DIRS  =  ( 
    # Pon cadenas aquí, como "/ home / html / django_templates" o "C: / www / django / templates". 
    # Usa siempre barras inclinadas, incluso en Windows. 
    # No olvides usar rutas absolutas, no rutas relativas. 
    os.path.join(os.path.dirname(__file__), 'templates').replace('\\','/'), 
)"""
"""staticfiles_dirs = (os.path.join(TEMPLATE_PATH,'static'),)
print(staticfiles_dirs)"""
# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/
STATIC_URL = '/static/'
STATIC_PATH = os.path.join(PROJECT_PATH,'static')
STATICFILES_DIRS = (
    STATIC_PATH, 
)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(PROJECT_PATH, 'media') # Absolute path to the media directory
LOGIN_URL = '/rango/login/'
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/


